# Copyright (c) 2015 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

platform :ios, '8.1'
use_frameworks!

abstract_target 'Crosswalk-Sample' do
  pod 'crosswalk-ios', :path => '../../'
  target 'Sample'
  target 'SampleApp'
end

